### ISSUE TITLE
Introduce connector pipelines

### ISSUE THREAD

**Issue by widhalmt** [NETWAYS/ansible-role-logstash#49]
To make it easier to provide predefined pipelines we need a special sort of pipelines to connect them.

Some brainstorming:
* Build pipelines that only contain `redis` inputs and outputs
* Create a directory `/etc/logstash/conf.d/connectors` and place single files there
* Make sure it works with all of the below:
  * One output
  * Two outputs
  * Three or more outputs

The configuration could look like:

```
logstash_connectors:
  - input
    - name: syslog
    - name: icinga
  - output:
    - name: sshd
    - condition: program == sshd
    - name: dhcpd
    - condition: program == dhcpd
  - catchall: forwarder
```

We need an extensive addon to `README.md` or even a separate `doc/` directory to explain how this can be used.
